### ISSUE TITLE
Actividad 4 Erik Cuevas Hernández 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-4-mapa-mental-ErikCuevas03#1]
![COMUNICACIÓN
ORAL Y ESCRITA_202283_64626](https://user-images.githubusercontent.com/112439930/191496998-07cf0719-79c1-42e3-b3be-2d222350d9fa.png)

**Comment by Daisy-GonzalezLita12** [comment]
17.8 de 20, ya que le faltó creatividad

**Comment by josealfredo79** [comment]
Bien hecho y revisado
